test/run.test.js
Fixing this required I assert that the type of stddev is a number, instead of a truthy value.
=> Fixed #11: failing tests when stddev was === 0

README.md, autocannon.js, lib/progressTracker.js, lib/run.js, test/run.test.js
Users can pass `renderProgressBar: true` to render the
progress bar from an external tool. Additionally, they
can provide `progressBarString: SOME_STRING` to modify
the output format of the progress bar. This string must
meet the format specified in npm.im/progress
This will require a review.
Additionally... how should I test this?
=> Fixes #10: Render progress bar programmatically.

README.md, lib/myhttp.js, lib/run.js, samples/modifying-request.js, test/myhttp.test.js
You need to call `.setHeaders(newHeaders)` and `.setBody(newBody)` for modifying these values. The reason you can't shouldn't just assign `.body` is because they are used to build a cached request, and simply overwriting it would mean I would have to un-cache the request and build it every time the client makes the request, because wouldn't be able to effectively and efficiently detect when it has been changed... simply put, its a big no-no for perf. 😄
If you do need to assign directly to the body though, it is possible, you just need to rebuild your request like so:
```js
const instance = autocannon({
url: url,
connections: 1000,
duration: 10
}, finishedBench)
instance.on('response', function (client, statusCode, returnBytes, responseTime) {
client.setHeaders({ .. })
client.body = ... …
```
=> fixes #9: Can now change headers and body on client response

README.md, lib/myhttp.js, lib/run.js, samples/customise-individual-connection.js, test/myhttp.test.js
This has the code, the docs and a sample. No unit tests right now however, I'm unsure how to test this.
fixes #16
=> Fixed #16: can now pass customiseRequest to build custom requests per connection

README.md, autocannon.js, help.txt, lib/progressTracker.js
=> fixed issue where latency table was never rendered

README.md, lib/httpClient.js
=> pass headers and body of replies through client events

lib/httpClient.js, test/helper.js, test/httpClient.test.js
If a response has trailers, it will trigger the following:
https://github.com/creationix/http-parser-js/blob/master/http-parser.js#L353
We need a noop for kOnHeaders otherwise autocannon will throw when a response has trailers
cc @mcollina
=> kOnHeaders bugfix

README.md, autocannon.js, help.txt, lib/httpClient.js, lib/run.js, test/runRate.test.js
Boom! No change in perf.
```
Glens-MacBook-Pro-2:autocannon glen$ ./autocannon.js -c 1000 -d 30 http://localhost:3000
Running 30s test @ http://localhost:3000
1000 connections
Stat         Avg     Stdev     Max
Latency (ms) 51.7    18.15     631
Req/Sec      19183.6 1286.36   20975
Bytes/Sec    2.13 MB 144.66 kB 2.36 MB
575k requests in 30s, 63.88 MB read
6 errors (0 timeouts)
```
Fixes #27 
Example usage:
```
Glens-MacBook-Pro-2:autocannon glen$ ./autocannon.js -R 10 -c 2 -a 100 http://localhost:3000
Running 100 requests test @ http://localhost:3000
2 connections
Stat         Avg     Stdev    Max
Latency (ms) 0.4     1.77     12
Req/Sec      10      2.24     15
Bytes/Sec    1.12 kB 254.04 B 1.73 kB
100 requests in 10s, 11.1 kB read
```
=> added rate limiting options

lib/run.js
Bumps max throughput to 100GB/s.
Fixes: https://github.com/mcollina/autocannon/issues/82
=> Bump max throughput to 100GB/s

README.md, autocannon.js, help.txt, lib/progressTracker.js, lib/run.js, package.json, test/forever.test.js
+ tests & documentation
fixes #92 
No perf damage over multiple runs.
=> Add functionality to run autocannon forever.

README.md
This patch removes Benchmarks header link from table of content as the
section isn't present anymore.
=> README: remove non existent benchmarks header from toc

lib/progressTracker.js
`stat.max` have already been converted to a human readable string containing the appropriate unit, so there's no need to format it further.
=> Fix bytes/sec max NaN output

lib/progressTracker.js
=> Reintroduce max two decimals in max column output

README.md, autocannon.js, help.txt, lib/httpClient.js, lib/run.js, test/helper.js, test/run.test.js, test/unixSocket.test.js
With this you can tell autocannon to send requests to a UNIX socket instead of a TCP socket, e.g:
```
autocannon /tmp/my-server.sock
```
For use with test HTTP server:
```js
const http = require('http')
http.createServer(function (req, res) {
res.end('Hello World')
}).listen('/tmp/my-server.sock')
```
=> Use autocannon on a UNIX socket

package.json, test/cli-ipc.test.js
The new tap v11.1.0 improves the ability to disable `autoend`, which means we can use t.tearDown even if we don't know call t.plan again.
See:
https://github.com/tapjs/node-tap/commit/fcf70aad8582d434658b8d3fe794e6ee463bcd2d
P.S. this was JUST released, so I unfortunately couldn't have included this in my last PR 😅
=> Clean up use of teardown

README.md, autocannon.js, help.txt, lib/progressTracker.js, lib/run.js, test/cli-ipc.test.js, test/run.test.js
Previously the Host header was always `localhost` when connecting to a Unix Domain Socket or a Windows Named Pipe. It was also not possible to use any other path than `/`.
With this commit the URL is always treated as a URL and if you want to supply a Unix Domain Socket or Windows Named Pipe, you instead have to provide it using `--socketPath` (aliased `-S`).
=> Allow use of http host and path during IPC

lib/defaultOptions.js, lib/run.js, package.json, test/run.test.js
I get something wrong when I run two autocannon benchmark at same time. However if I run these benchmarks separately it works fine.
example:
```js
const autocannon = require('autocannon');
const util = require('util');
const autocannonFunc = util.promisify(autocannon);
function setupClient {
...
}
async function login() {
try {
return await autocannonFunc({
url: 'http://192.168.0.245:10000/login',
connections: 15,
pipelining: 1,
amount: 15,
bailout: 1,
method: 'POST',
setupClient,
});
} catch(err) {
...
}
}
async function register() {
try {
return await autocannonFunc({
url: 'http://192.168.0.245:8888/register',
connections: 1,
pipelining: 10,
amount: 20,
bailout: 1,
method: 'POST',
headers: {
'Content-Type': 'application/json',
},
body: JSON.stringify(body),
});
} catch(err) {
...
}
} …
```
=> fix default option issue

README.md, autocannon.js, help.txt, lib/defaultOptions.js, lib/httpClient.js, lib/run.js, test/helper.js, test/httpClient.test.js
Server Name Indication (SNI) is an extension to TLS by which a client indicates which hostname it is attempting to connect to at the start of the handshaking process. This allows a server to present multiple certificates on the same IP address.
https://en.wikipedia.org/wiki/Server_Name_Indication
=> Added optional server name for the SNI TLS extension

README.md, autocannon.js, help.txt, test/envPort.test.js
If the `$PORT` env variable is set, the URL defaults to
`localhost:PORT/path`. You can pass a bare path for the URL.
This allows doing:
0x --on-port 'autocannon /path' -- node server.js
When an invalid URL is given, autocannon now logs an error and exits.
(`/path` without a `$PORT` is an invalid URL.)
It uses the URL API which was backported to Node 6.13.0, if lower
versions of Node 6 should be supported I can change it to use
`url.parse` and `url.format` instead.
=> Target localhost by default if $PORT is set, closes #146.

lib/run.js
1 significant digit seems too low, this makes only first digit relevant. 
3 seems a good balance between precision and memory footprint
=> Fix throughput stats

README.md
As requested in #144
I just mentioned what the different fields mean in a pretty basic sense, and what values users should be hoping for (high/low). I don't know much of anything about the statistical significance so I didn't add anything about that.
I included the -l latency table for completeness but it seems less useful now that the small default latency table already lists key percentiles...
=> Explain the CLI table output in the readme

lib/run.js, test/runRate.test.js
Fixes the issue - when connections are greater than overallRate, overallRate doesn't work as intended and req/sec exceed overallRate specified.
=> fix for rate limit issue #187

lib/run.js, test/run.test.js
First time submitting a PR ever. I tried adding to checkOptsForErrors() function, but that just resulted in about 70 failed tests, adding the throw was **a lot** easier.
=> Check to prevent infinite loop when amount is greater than connections

lib/httpClient.js, test/httpClient.test.js
I received the following error for `opts.pipelining` value > 1.
`this.resData.length` always returned 1 for me.
[length source](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-properties-of-array-instances-length)
```
TypeError: Cannot set property 'startTime' of undefined
at Client._doRequest (/Users/testing/Documents/Github/benchmark/node_modules/autocannon/lib/httpClient.js:146:33)
at Client._connect (/Users/testing/Documents/Github/benchmark/node_modules/autocannon/lib/httpClient.js:135:10)
at new Client (/Users/testing/Documents/Github/benchmark/node_modules/autocannon/lib/httpClient.js:100:8)
at initialiseClients (/Users/testing/Documents/Github/benchmark/node_modules/autocannon/lib/run.js:214:20)
at _run (/Users/testing/Documents/Github/benchmark/node_modules/autocanno …
```
=> TypeError: Cannot set property 'startTime' of undefined

README.md, lib/run.js, test/run.test.js
This PR adds the necessary logic to propagate the `counter` on the `tick` event. The new adjustments are also covered by integration tests.
=> Propagate counter on tick

autocannon.js, help.txt, lib/run.js, test/debug.test.js
This patch adds ` --debug` flag that prints connection errors to `stderr`.
I've been messing around with HTTP parsers recently, and autocannon is a great way to test how well a server works. Being able to see errors are happening is usually a good indicator things are broken. And having a way to print out *what* those errors are is really convenient. So hence this patch.
Hope this is useful. Thanks!
=> add option to print errors

lib/httpClient.js, lib/httpRequestBuilder.js, test/basic-auth.test.js, test/helper.js, test/httpClient.test.js, test/httpRequestBuilder.test.js
=> adds support for HTTP basic authentication

lib/httpRequestBuilder.js, test/httpClient.test.js, test/httpRequestBuilder.test.js, test/requestIterator.test.js
Fix #229 
Also, update tests
Result for uWS
```
$ ./autocannon.js -c 100 -p 100 -d 10 -m POST -b '{"a":1}' http://0.0.0.0:8080
Running 10s test @ http://0.0.0.0:8080
100 connections with 100 pipelining factor
┌─────────┬──────┬──────┬───────┬───────┬─────────┬──────────┬───────────┐
│ Stat    │ 2.5% │ 50%  │ 97.5% │ 99%   │ Avg     │ Stdev    │ Max       │
├─────────┼──────┼──────┼───────┼───────┼─────────┼──────────┼───────────┤
│ Latency │ 0 ms │ 0 ms │ 0 ms  │ 17 ms │ 3.29 ms │ 34.33 ms │ 798.73 ms │
└─────────┴──────┴──────┴───────┴───────┴─────────┴──────────┴───────────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev  │ Min     │ …
```
=> Fix bug with \r\n tail in requests with body

autocannon.js, test/argumentParsing.test.js
As documented header parsing should support arguments like
`-H "Date=Wed Jan 01 2020 20:02:36 GMT+0800 (Hong Kong Time)"`.
Currently the header would be sent as
`Date=Wed Jan 01 2020 20: 02:36 GMT+0800 (Hong Kong Time)`.
Fixes: https://github.com/nodejs/node/issues/31023
=> fix: parse argument with ":" in value header

README.md, help.txt, lib/multipart.js, test/helper.js, test/runMultipart.test.js
Fix Content-Disposition header writing by exposing `form-data` `.append()` method options
in the `options` key of the form object when the type is `file`.
This allows passing a custom `filename` or `filepath` for a file. By default the `filename`
is set to the file name passed in the `path` key.
See:
* https://github.com/form-data/form-data/tree/v2.5.1#alternative-submission-methods
* https://github.com/form-data/form-data/tree/v2.5.1#void-append-string-field-mixed-value--mixed-options-
Fix #240 
@mcollina  I don't know if this is clear enough. Maybe I should add some examples.
=> fix: multipart form handling

README.md, autocannon.js, help.txt, lib/httpClient.js, lib/progressTracker.js, lib/run.js, test/helper.js, test/run.test.js
This is probably a niche need driven by my paranoia. However, for certain scenarios it adds peace of mind knowing that the server sent what I expected it to back to the client. While this isn't necessarily the place of a benchmarking tool, it is helpful to me to have this for stress testing sorts of purposes.
I understand if it doesn't fit. That being said it's mostly an unobtrusive addition. The only thing it really imposes is the addition of `mismatches` to the API results. I suppose I could have fenced that off so that it only shows in the results if the option is enabled. Let me know if that would be desirable and I can do that.
=> Add expectBody option and related tests

test/runMultipart.test.js
Validate the parsed form returned by the test server in all test cases.
=> test(runMultipart): validate form payload in all cases

lib/httpClient.js, lib/requestIterator.js, test/httpClient.test.js, test/requestIterator.test.js
In my previous PR #261, I misunderstood how `http-parser-js` works, and I introduced an issue.
Assuming a server which returns "hello" on POST and "world" on GET, and the following request array:
```js
[{
method: 'POST'
onResponse(status, body) {
console.log('POST', body)
}
}, {
method: 'GET'
}]
```
would produce output:
```bash
POST hello
POST world
```
The reason is because when a request has `onResponse()`, httpClient goes to next request on body received event, instead of message complete event. I thought body event was issued after message complete, which is completely wrong.
I've restored previous sequence, which is going to next request on message complete event, regardless of the request type.
Finally, http client will now keep a reference to requests instead of letting …
=> fix: onResponse sequence

autocannon.js, lib/run.js, lib/url.js, test/argumentParsing.test.js, test/runMultiServer.test.js
This is a non-breaking-change feature
When we bench a distributed system across continents (such as a blockchain system), there is often no load balancing. At this time, if it supports natively multi-node bench, it will be very convenient.
Added a compatible new feature to support multiple URLs like this
```
autocannon http://localhost:1234 http://localhost:1235
```
also programmatically supported with
```js
const autocannon = require('autocannon')
autocannon({
url: ['http://foo.bar:3000', 'http://baz.qux:3001']
})
```
=> Add a new feature to support run with multiple url

README.md, samples/bench-multi-url.js
add some example for benching with multiple urls
=> chore: sample for multi nodes

README.md, autocannon.js, help.txt, lib/httpClient.js, lib/run.js, test/runRate.test.js
Hello!
This is a small PR to add a `correct coordinated omission` feature to autocannon. 
It works with either connectionRate or overallRate options. 
I have left it deactivated by default since the impact on the displayed latencies can be quite significant...
Let me know if you need me to do any change
=> feat: add a correct coordinated omission option

README.md, help.txt, lib/httpClient.js, test/helper.js, test/httpClient.test.js
Default to sending the SNI servername when the `servername` option is not present or falsy. This behaviour matches browsers as well as popular tools like `curl` or `openssl s_client`.
Fixes: https://github.com/mcollina/autocannon/issues/233
=> Enable SNI servername by default

README.md, lib/httpRequestBuilder.js, lib/requestIterator.js, test/requestIterator.test.js
`setupRequest()` is very handy to perfom dynamic scenarios.
However, users do not necessarily realize they have to return a request object. If they don't, it'll crash the whole benchmark.
Besides a very common need is to skip the rest of the scenario.
This feature fixes both, by reset request iterator based on `setupRequest()`.
=> feat: restart request iterator when setupRequest returns falsey

README.md, lib/httpClient.js, lib/progressTracker.js, lib/requestIterator.js, lib/run.js, test/httpClient.test.js, test/progressTracker.test.stub.js, test/requestIterator.test.js, test/run.test.js
This is a follow up of #281 
Now, request iterator resets when some of its `setupRequest()` returning falsey value (previously it the pipeline was simply crashing).
But this may actually obfuscate bugs of the tested service: often `setupRequest()` fails as the previous response did not contained expected data.
This PR simply displays how many times the pipeline reseted, so users could decide whether it is intended or not.
```shell
┌─────────┬────────┬────────┬────────┬────────┬───────────┬───────────┬────────────┐
│ Stat    │ 2.5%   │ 50%    │ 97.5%  │ 99%    │ Avg       │ Stdev     │ Max        │
├─────────┼────────┼────────┼────────┼────────┼───────────┼───────────┼────────────┤
│ Latency │ 121 ms │ 624 ms │ 890 ms │ 914 ms │ 541.06 ms │ 237.32 ms │ 1002.16 ms │ …
```
=> feat: report many pipeline resets

lib/run.js, package.json, test/serial/wasm.test.js
Hello
This PR is related to [issue 272](https://github.com/mcollina/autocannon/issues/272)
The two things that are very important when using wasm histograms are to load the binary prior to instantiation and to free the memory when the histograms are not needed anymore.
Let me know if you prefer to enable wasm histograms only when a config switch is on.
=> Enable WASM for HdrHistogramJS

.taprc, lib/httpClient.js, test/helper.js, test/run.test.js
We have noticed in our API use of autocannon that `onResponse` callback are not invoked if the server sends no body.
This PR fixes the issue.
=> fix: Record bodies in the RequestIterator even if the body is empty.

README.md, package.json
Explain a bit more the implied limitations of autocannon.
=> Limitations

lib/httpClient.js, test/httpClient.test.js, test/run.test.js
Supersedes https://github.com/mcollina/autocannon/pull/276/files
Fixes https://github.com/mcollina/autocannon/issues/275
Coincidently this fix also over-rides the code changes one done in https://github.com/mcollina/autocannon/pull/287 but the fix still works.
- Refactored response body parsing. It now collects body chunks until `kOnMessageComplete` fires and then it calls `onResponse` and emit `response`
- Added test to cover the same
=> fix: handle large response body correctly

README.md, lib/httpClient.js, lib/run.js, test/helper.js, test/httpClient.test.js
**Why**
Currently there is no way to pass custom client certificates through autocannon if the server being benchmarked requires client certificate validation
**How**
- Adding support in the js API to pass in tlsOptions through to the httpClient.
- Updated the test tls server to echo the client certificate email as a way to verify things are working correctly
=> Adding support for passing in custom tlsOptions

README.md, lib/requestIterator.js, lib/run.js, samples/init-context.js, test/httpClient.test.js, test/requestIterator.test.js, test/run.test.js
Fixes https://github.com/mcollina/autocannon/issues/279
- Added `initialContext` option which is used to initialize context instead of empty object
- Covered with tests
- Updated readme.
=> feat: Add support for initializing custom context object

test/httpClient.test.js, test/runRate.test.js
Builds are still not very stable on windows CI.
Although we tried running on windows machine locally but could never see a test fail.
It seems like these two tests in `httpClient.test.js` are failing intermittently. 
- client should emit a timeout when no response is received
- client should emit 2 timeouts when no responses are received
This PR increases wait time from 2500 to 2800, just so slow windows boxes don't choke up. 
All 3 scenarios of the following test are failing intermittently. 
- run should only send the expected number of requests per second
I presume the `duration` may be coming as slightly more than 4.5 seconds due to slow windows box and becomes `5` due to `Math.round`. But we're asserting it with `4`, so I've changed it to `Math.floor` instead.
=> fix: attempt to fix intermittent test failures

README.md, help.txt
Fix "autocannnon" misspelling in help text and README.
=> docs: s/autocannnon/autocannon/ in help.txt and README.md

lib/httpClient.js, test/helper.js, test/httpClient.test.js
Fixes https://github.com/mcollina/autocannon/issues/315
=> fix (#315): correctly increment this.cer

test/httpClient.test.js
Tests are failing on MacOS 10. May be 600 ms isn't enough time, so increased it to 800
=> fix: test checking duration of request with pipeline

autocannon.js, lib/util.js, lib/validate.js, lib/worker_threads.js, test/cli.test.js, test/run.test.js, test/runMultipart.test.js, test/workers.test.js
Fixes https://github.com/mcollina/autocannon/issues/324
=> fix(324): Show error when no worker support is found

test/helper.js, test/run.test.js
```js
const server = http.createServer((req, res) => {
res.statusCode = 102
res.end('Hello')
})
server.listen(9000)
```
This simple http server responds differently in Node v14 vs v15. 
**Response in Node v14**
```
HTTP/1.1 102 Processing
Date: Thu, 21 Jan 2021 15:22:09 GMT
Connection: close
```
**Response in Node v15**
```
HTTP/1.1 102 Processing
Date: Thu, 21 Jan 2021 15:22:09 GMT
Connection: close
Content-Length: 5 // <---
```
I haven't done a thorough research with node and http specs as to why this behaviour is different but as I understand, the `102` response doesn't return a body. But if you try to send it, Node 14 smartly ignores it and does not send a `Content-Length` header. However Node 15 sends this header, which is why `http-parser-js` waits for the body and never fires …
=> fix: broken test with node 15

lib/requestIterator.js, test/requestIterator.test.js
Thanks for creating and maintaining `autocannon`. I really enjoy using this software.
I was running tests on an AWS API Gateway where I needed to configure a fixed set of headers for a couple of requests when I encountered the same issue as in #280 .
I went ahead and tried to fix it. All feedback is welcome and I'll try to update as quick as possible.
=> fix: Reuse headers when set - fixes #280

test/httpClient.test.js
In addition it's probably better to use a t.setTimeout(..) than assertion for a timeout because it will come with a clear and informative error message.
=> Remove unnecessary timeout check in httpClient delay test

lib/httpClient.js, package.json, test/httpClient.test.js
@mcollina this should help further.
However, I don't like the fix here because as a user of `httpClient` I would expect for `client.destroy()` to work regardless of when it is called. In the current implementation, `client.destroy()` will not work as expected if invoked synchronously in a timeout handler. It does not clear the retry mechanism of the `httpClient`.
I think the "right" fix consists in using a different version of `retimer` that allows to reset the timer after it has been triggered. This way there is no need to change the instance of retimer within the `httpClient`.
Cf. https://github.com/mcollina/autocannon/blob/f8b598e103644e5048f9a936d6ac3b746986285e/lib/httpClient.js#L73
=> Update some more tests relying on timeouts

lib/progressTracker.js, package.json, test/cli.test.js, test/progressTracker.test.js
Replaces ora with char-spinner to avoid the warning altogether.
I didn't actually figure out the root cause of why this is happening, and I do realize that making this initialization eager is doing something that's probably unnecessary unless workers are being used. Nevertheless, that's the most reliable way I found to fix this.
The problem seems to come from the bl package used by ora, which does some fancy stream manipulation, eventually leading to the warnings being generated.
Making the initialization of ora eager in the module root makes the issue disappear. 
Closes #337
=> fix: do not show warnings when workers >= 10

lib/httpClient.js, lib/pipelinedRequestsQueue.js, package.json, test/httpClient.test.js, test/pipelinedRequestsQueue.test.js
This PR mostly brings 2 changes:
1. It extracts the previous [cer/rpi](https://github.com/mcollina/autocannon/pull/317/files#r543678831) logic into a specialized queue`PipelinedRequestsQueue`.
2. It adds asserts and tests to ensure the reported response time is bound between the induced delay and the observed response time, from the test's perspective
=> Ensure there are tests for calculating the duration of pipelined requests

test/progressTracker.test.js, test/progressTracker.test.stub.js
- restore original progressTracker test stub which was not intended to be run automatically
- move test which checks warnings into own module and run it with suppressed output
=> fix: suppress test output

README.md, autocannon.js, help.txt, lib/init.js, lib/progressTracker.js, lib/subargAliases.js, package.json, test/run.test.js, test/subargAliases.test.js
Closes: https://github.com/mcollina/autocannon/issues/202
To test add a warmup flag to the command line or in the config: Eg
```
node autocannon -c 3 -d -W [ -c 2 -d 2 ] http://localhost:5000
```
or
```
node autocannon -c 3 -d --warmup [ --connections 2 --duration 2 ] http://localhost:5000
```
- Check that it works in both command line and imported modes
- Check that additional flags are being correctly utilised and aliased 
- Check that the display on the command line whilst running is displaying the warmup
- Check that the final reported stats do not include the warmup period
- Due to refactoring in `lib/init` check that all calls to `init` work as expected.
- Replaces `minimist` with `subarg` so that we can include subarguments such as `--warmup`. `subarg` uses `minimist` internally so …
=> Feat: Add a warmup option

lib/requestIterator.js, test/httpClient.test.js, test/requestIterator.test.js
This PR aims to fix a behavior expected in https://github.com/rafaelGSS/autobench#config-file by specifying `headers` inside `opts.requests`.
Currently, the lib isn't using `request[index].headers` in the requests, this PR should solve it.
=> fix: use headers from requests if any

README.md
A short paragraph explains the distribution algorithm of fixed amounts of requests and non-intege divisible overallRate limits over the number of connections.
=> Add overallRate distribution to README.md

help.txt
`--har` option is present in the [representation of the CLI options in the readme](https://github.com/mcollina/autocannon#command-line) but is missing from the actual CLI output when running `autocannon -h`
=> fix(help): add missing `--har` option

README.md
**2.29MB** correspond to the amount of data dowloaded in **1 second** in the worst case, while the entire test took **10 seconds** to complete.
Related with #395 and #363
=> Update: example values in readme

autocannon.js, help.txt, lib/defaultOptions.js, test/sampleInt.test.js
[This PR](https://github.com/mcollina/autocannon/pull/425) is causing unexpected behavior in some measurements:
https://github.com/fastify/benchmarks/issues/233 and I believe for most of the users is better to use default as `1000` at least is more readable than:
```
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min   │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼───────┤
│ Req/Sec   │ 16      │ 32      │ 55      │ 89      │ 54.75   │ 11.09   │ 1     │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼───────┤
│ Bytes/Sec │ 2.99 kB │ 5.99 kB │ 10.3 kB │ 16.7 kB │ 10.2 kB │ 2.07 kB │ 187 B │
└───────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴───────┘
Req/Bytes counts sampled every 0.001 …
```
=> update: use sample interval default 1000

README.md, autocannon.js, test/argumentParsing.test.js
Currently the only way to pass custom cert information to autocannon is via the `tlsOptions` in the autocanno js api. This PR adds the ability to pass in common cert information from the cli tool so that consumers can easily use autocannon without writing a custom script.
- Add logic in autocannon.js to parse arguments and read the relevant files
- Normalize all the arguments to be part of the `tlsOptions` key so that the `httpClient.js` can get the correct values
=> Add cli options to pass cert information

.github/workflows/nodejs.yml
Declares the minimum [permissions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) for CI workflows to run at the job level, following principle of least privilege; see [related GitHub security post](https://securitylab.github.com/research/github-actions-building-blocks/)
=> ci: reduce job permissions to minimum

autocannon.js, lib/parseHAR.js, lib/run.js, lib/validate.js, lib/worker.js, package.json, samples/bench-multi-url.js, samples/customise-individual-connection.js, samples/init-context.js, samples/modifying-request.js, samples/request-context-workers.js, samples/request-context.js, samples/requests-sample.js, samples/using-id-replacement.js, test/httpRequestBuilder.test.js
closes #445 by making fixes standard 17 highlights
=> build(deps-dev): bump standard from 16.0.4 to 17.0.0

README.md, help.txt
The --help output was outdated to what was in README. Synced the content
from the readme into help.txt and did one minor formatting change.
=> fix: Sync --help output with README

.github/workflows/nodejs.yml, lib/httpRequestBuilder.js, lib/util.js, test/httpClient.test.js
This makes CLI `-H 'Host: foo'` work where previously it did not identify the header correctly because it was case-sensitive.
=> Accept host header case-insensitively

README.md
`wrk` doesn't handle coordinate omission. Furthermore, autocannon is based on `wrk2`.
=> doc: change recomendation to wrk2 instead wrk

README.md
Adds missing documentation for `-L` param (copied from help.txt).
Adds more comprehensive documentation of workers mode and parameter behaviour there.
=> Add missing param docs. Fuller docs on worker mode

samples/customise-individual-connection.js
trying with node version v16.14.2 I get this error 
```
node samples/customise-individual-connection.js 
/Users/.../workspace/autocannon/samples/customise-individual-connection.js:27
client.setBody('connection number', connection++)
^
ReferenceError: Cannot access 'connection' before initialization
... 
... 
```
=> fix Cannot access 'connection' before initialization

README.md, autocannon.js, lib/aggregateResult.js, lib/run.js, test/aggregateResult.test.js
This update introduces the ability to coordinate a load test using multiple separate machines running autocannon against an API, whilst still being able to use the built-in result aggregation functionality, as if it were using connections and/or worker threads on a single machine.  It is a lightweight and backward-compatible.
To keep things simple in autocannon, the implementation of the coordination between machines is left as the responsibility of the consumers of this library, as there are undoubtedly many possibilities.
=> Defer aggregating results until after the instance returns to allow multi-instance load tests

lib/printResult.js
Before:
```
[1] ┌───────────┬─────────┬─────────┬─────────┬─────────┬────────────┬──────────┬─────────┐
[1] │ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg        │ Stdev    │ Min     │
[1] ├───────────┼─────────┼─────────┼─────────┼─────────┼────────────┼──────────┼─────────┤
[1] │ Req/Sec   │ 126719  │ 126719  │ 146815  │ 149759  │ 142995.21  │ 8486.98  │ 126696  │
[1] ├───────────┼─────────┼─────────┼─────────┼─────────┼────────────┼──────────┼─────────┤
[1] │ Bytes/Sec │ 23.8 MB │ 23.8 MB │ 27.6 MB │ 28.1 MB │ 26.9 MB    │ 1.6 MB   │ 23.8 MB │
[1] └───────────┴─────────┴─────────┴─────────┴─────────┴────────────┴──────────┴─────────┘
```
After:
```
[1] ┌───────────┬─────────┬─────────┬─────────┬─────────┬────────────┬──────────┬─────────┐
[1] │ Stat      │ 1%      │ 2.5% …
```
=> improve string output for Req/Sec

README.md
Following the work done [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67300)
=> docs(readme): Add missing result param

README.md, autocannon.js, lib/printResult.js, test/printResult.test.js
This PR adds a new option to the CLI `--V` to manage the verbosity of the output. Sometimes (mostly for automation) we just need the last line output:
```console
$ ./autocannon.js -V=0 -c 100 -d 30 localhost:3000
Running 30s test @ http://localhost:3000
100 connections
44k requests in 30.02s, 8.06 MB read
```
By default verbose is `true` so nothing will change to regular users.
=> lib: add verbose option

README.md
=> doc: adjust alignement

lib/httpRequestBuilder.js, test/httpRequestBuilder.test.js
fixes https://github.com/mcollina/autocannon/issues/502
=> allow only one host header

README.md
=> doc: fix API autocannon.print

lib/requestIterator.js, test/requestIterator.test.js
=> fix(requestIterator): generated IDs were not URL-safe

lib/printResult.js, package.json, test/printResult.test.js
Fixes one of the two bugs described in #474
`$ node autocannon.js http://google.com/ --verbose > output.txt 2>&1`
```
Running 10s test @ http://google.com/
10 connections
^[[90m┌─────────^[[39m^[[90m┬──────^[[39m^[[90m┬──────^[[39m^[[90m┬───────^[[39m^[[90m┬──────^[[39m^[[90m┬──────^[[39m^[[90m┬───────^[[39m^[[90m┬──────┐^[[39m
^[[90m│^[[39m^[[31m Stat    ^[[39m^[[90m│^[[39m^[[31m 2.5% ^[[39m^[[90m│^[[39m^[[31m 50%  ^[[39m^[[90m│^[[39m^[[31m 97.5% ^[[39m^[[90m│^[[39m^[[31m 99%  ^[[39m^[[90m│^[[39m^[[31m Avg  ^[[39m^[[90m│^[[39m^[[31m Stdev ^[[39m^[[90m│^[[39m^[[31m Max  ^[[39m^[[90m│^[[39m
^[[90m├─────────^[[39m^[[90m┼──────^[[39m^[[90m┼──────^[[39m^[[90m┼───────^[[39m^[[90m┼──────^[[39m^[[90m┼──────^[[39m^[[90m┼───────^[[39m^[[90m┼──────┤^[[39m
^[[90m│^[[39m Latency ^[[90m│^[[39m 0 ms …
```
=> fix(printResult): tables included colors even when outputStream did not support it

README.md
As a user of Autocannon, it took far too long to figure out why the idReplacement system was not working. Ultimately it was the source code which revealed that replacement target was, _in its entirety_, `[<id>]`. It's a bit unusual to have a two character wrapper where both characters are different, so we interpreted the square braces as a code container in the same way backticks might be used. It appears in other parts of the README, you've used backticks to better represent that the entire string is the target. So I've updated the command line example with this as well.
=> Update README to make behavior of idReplacement more clear

lib/requestIterator.js, test/requestIterator.test.js
=> Allow for ID replacement in the URL

.github/workflows/nodejs.yml, README.md, autocannon.js, test/onPort.test.js
Adds support for #180 
@mcollina Please review when you have some time.
=> assume onPort if -- node is set
