mcollina/autocannon

- README.md
- package.json
> Bumped native-hdr-histogram and README.

- autocannon.js
- help.txt
- lib/myhttp.js
- test/myhttp.js
Fixes #1 and #2.
@davidmarkclements please review :)
> --body is for an inlining. Added --input to specify the body from a file. body as strings.

- README.md
- lib/myhttp.js
- lib/run.js
- test/run.test.js
I will need my other PR to be merged to finish the work on defaults, as there is clashing details between this PR and my other
Fixes #19
> update docs and defaults

- README.md
- autocannon.js
- help.txt
- lib/progressTracker.js
- lib/run.js
- package.json
- test/run.test.js
Some docs were updated too. The command line option for body was changed, as I thought `-H` for headers and `-B` for the body was a nice piece of consistency.
> Fixed #21: added a bailout option.

- README.md
- help.txt
- lib/myhttp.js
- lib/progressTracker.js
- lib/run.js
- package.json
- test/helper.js
- test/myhttp.test.js
fixes #23 
This will reset a connection when a timeout occurs, because that seemed like the proper approach to clearing all pipelined reqs
> added timeout feature

- lib/httpClient.js
> Smart default for https port and propagate error

- lib/run.js
- test/helper.js
- test/run.test.js
Should this be considered the solution to #46 (non 200's not recorded)?
> now results have status codes

- README.md
- lib/run.js
- package.json
- test/run.test.js
This is more of a vanity option, but I figured it might be nice after seeing how a user was trying to use autocannon in #52
This will also fix #52
> allow users to enter Timestring's for duration

- lib/progressTracker.js
- package.json
- test/cli.test.js
Fixes #60.
@davidmarkclements @thekemkid please review.
> Avoid printing the progress bar if the destination is not a TTY.

- help.txt
- lib/progressTracker.js
General house keeping PR. drop any suggestions you might have for code cleanliness and understandability into the comments on this PR.
> clean up work

- lib/run.js
- test/run.test.js
> prepend url with http:// by default if it isn't there, and output url  in result json

- README.md
- samples/track-run.js
> added a track sample

- lib/progressTracker.js
- package.json
Fixes #59
I added color-support as a dependency as it accomplishes what we need.
> better color support testing

- lib/run.js
> Correctly handle duration if it is a boolean

- autocannon.js
> don't render results table when -n arg is passed

- lib/httpRequestBuilder.js
I needed PATCH for testing a PATCH based API. 
Tested this manually with my PATCH API.
> Adding PATCH

- lib/httpMethods.js
- lib/httpRequestBuilder.js
- test/httpClient.test.js
- test/httpRequestBuilder.test.js
I listed them in the order they're presented here: https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Summary_table
> Added all http methods/verbs

- README.md
- autocannon.js
- help.txt
- lib/defaultOptions.js
- lib/run.js
- test/run.test.js
> Support excluding error statistics from latency and bytes per second averages

- lib/run.js
- test/helper.js
- test/run.test.js
> Pass error to reqError listener

- autocannon.js
> Support standard syntax for HTTP headers

- lib/httpRequestBuilder.js
- package.json
- test/httpClient.test.js
Add the possibility to set the `host` header.
> Fix issue with host header

- autocannon.js
- test/argumentParsing.test.js
> Update HTTP Headers parsing logic

- lib/progressTracker.js
Fixes https://github.com/mcollina/autocannon/issues/177.
@Youjingyu  can you please verify?
> Initialize things only after start is emitted

- package.json
> chore(package): update tap to version 13.1.8

- README.md
- lib/run.js
- test/run.test.js
Feature: support promise API.
Modify test cases `throw if connections is greater than amount`: add a noop callback in this test case.
New test case `run promise`: copied from case `run`, use then instead of callback
> Feature/promise api refs #186

- lib/run.js
- test/run.test.js
> Fix min req/sec when 0 requests succeed

- lib/progressTracker.js
- lib/run.js
- package.json
- test/helper.js
- test/httpClient.test.js
- test/httpRequestBuilder.test.js
- test/progressTracker.test.stub.js
- test/requestIterator.test.js
- test/run.test.js
- test/serial/autocannon.test.js
- test/serial/run.test.js
Test coverage 100% on lines
@mcollina running tests reports a full 100% coverage on all metrics but some files are missing. This happened when I added `serial/autocannon.test.js` . If you run tests without that file you'll have 100% coverage an all files under `./lib`. Can you have a look?
> Improve test coverage

- test/httpClient.test.js
> chore: more and simpler tests on http client

- lib/requestIterator.js
- test/requestIterator.test.js
> fix: unique idReplacement on every request

- .github/dependabot.yml
- .github/workflows/nodejs.yml
- .taprc
- package.json
- Added dependabot and auto merge
- Increased tap timeout to 5 min
> chore: add dependabot automerge

- .taprc
- lib/aggregateResult.js
- test/workers.test.js
- Added workers option in the output
- Added a test for workers
> fix: add workers in the output

- .taprc
- autocannon.js
- lib/init.js
- lib/manager.js
- lib/progressTracker.js
- lib/runTracker.js
- package.json
- test/cli.test.js
- test/runRate.test.js
- Fixed event emitter memory leaks
- Fixed progress tracker for workers mode
> fix: fixes (mem leaks, progress tracking)

- autocannon.js
- test/argumentParsing.test.js
BREAKING CHANGE: clients expecting the header to be trimmed will the get
wrong header
Closes https://github.com/mcollina/autocannon/issues/238
> fix(argument parsing): remove trim of headers

- .github/workflows/nodejs.yml
Fixes https://github.com/mcollina/autocannon/pull/371
> ci: add node 16 to test matrix; remove node 10

- README.md
- help.txt
> docs: grammar, spelling, and readability fixes

- lib/httpRequestBuilder.js
- test/httpClient.test.js
Fixes: https://github.com/mcollina/autocannon/issues/413
> fix: Fix JSON array body on CLI

- .github/workflows/nodejs.yml
This merges into dependabot's branch
> chore: use semver major of merge action

- .gitignore
- README.md
- lib/httpClient.js
- lib/run.js
- lib/validate.js
- lib/worker.js
- samples/customise-verifyBody-workers.js
- samples/customise-verifyBody.js
- samples/helpers/verify-body.js
- test/run.test.js
- test/utils/verify-body.js
- test/workers.test.js
Hey bro. 
This PR is about customize the mismatch rules for response body.  And i added samples and unit tests. Please contact me if you have any questions. 
tks so much
> feat: add `verifyBody` to customize the mismatch rules for response body
